<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="WIN-0960QI77CVH" failures="2" tests="2" name="Default test(failed)" time="0.048" errors="0" timestamp="2022-05-23T23:12:17 AMT">
  <testcase classname="demo.TestNG_RerunFailedDemo" name="test4" time="0.012">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at demo.TestNG_RerunFailedDemo.test4(TestNG_RerunFailedDemo.java:29)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test4 -->
  <testcase classname="demo.TestNG_RerunFailedDemo" name="test2" time="0.001">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at demo.TestNG_RerunFailedDemo.test2(TestNG_RerunFailedDemo.java:16)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="demo.TestNG_RerunFailedDemo" name="test1" time="0.0">
    <ignored/>
  </testcase> <!-- test1 -->
  <testcase classname="demo.TestNG_RerunFailedDemo" name="test3" time="0.0">
    <ignored/>
  </testcase> <!-- test3 -->
</testsuite> <!-- Default test(failed) -->
